### ISSUE TITLE
ENV['INLINEDIR'] can't be relative

### ISSUE THREAD

**Issue by tigris** [seattlerb/image_science#12]
I was setting ENV['INLINEDIR'] to "tmp", e.g. relative to my Rails.root, the correct files would get created, e.g. I have `Inline_ImageScience_cdabbf6be1583cf10d50065dbe0df70a.so` and `Inline_ImageScience_cdabbf6be1583cf10d50065dbe0df70a.c` in my `tmp/ruby_inline/ruby-1.9.1/` folder, however rails would still fail to boot saying it can't find `tmp/.ruby_inline/ruby-1.9.1/Inline_ImageScience_cdabbf6be1583cf10d50065dbe0df70a.so`.

Changing my ENV['INLINEDIR'] to `File.join Rails.root, 'tmp'` fixed my problem. I.e. using an absolute path over a relative one.

**Comment by zenspider** [comment]
This probably have everything to do with how you're deploying your rails app and really isn't an image_science issue. I'll make a note of it. Thanks for reporting.
