### ISSUE TITLE
raising error on warnings

### ISSUE THREAD

**Issue by bhenderson** [seattlerb/image_science#21]
https://f.cloud.github.com/assets/26167/962446/027b0198-04f0-11e3-9c07-3bae19ce7608.jpg

When trying to process this image, we get an error raised:

```
RuntimeError: FreeImage exception for type JPEG: Corrupt JPEG data: 49 extraneous bytes before marker 0xd9
```

if I comment out this line

https://github.com/seattlerb/image_science/blob/master/lib/image_science.rb#L176

it works.

I don't know how to link to the FreeImage source, but it looks like that message is coming from here:

Source/LibJPEG/jdmarker.c:946
    WARNMS2(cinfo, JWRN_EXTRANEOUS_DATA, cinfo->marker->discarded_bytes, c);

which looks like it should be a warning and not an error.
do you have any thoughts? I'm still trying to find documentation for FreeImage_SetOutputMessage.

**Comment by zenspider** [comment]
This should be fixed. Thanks!
