### ISSUE TITLE
Is this gem still supported?

### ISSUE THREAD

**Issue by Arepo** [seattlerb/image_science#26]
The http://seattlerb.rubyforge.org/ URL seems to be dead

**Comment by Nakilon** [comment]
@Arepo do you have any specific issue?  
There is also another gem that uses vips instead of rmagick: https://github.com/jcupitt/ruby-vips -- it has `resize` and `thumbnail` methods.

**Comment by zenspider** [comment]
@Arepo I'll repeat @Nakilon's question: do you have any specific issue?

To be clear, this gem doesn't use rmagick.

**Comment by zenspider** [comment]
10 days, no response. Closing.
